import type { LangFilter } from "@/types/search";

/**
 * Episode item returned by POST /api/search/episodes (v2).
 * Corresponds to EpisodeDto in podcast-spec.
 */
export interface EpisodeDto {
  episodeId: string;
  title: string;
  description: string;
  highlights: { title?: string[]; description?: string[] };
  publishedAt: string;      // ISO 8601
  durationSec: number;
  imageUrl: string;
  /** Language index this episode belongs to: "zh-tw" | "zh-cn" | "en" */
  language: string;
  podcast: {
    podcastId: string;
    title: string;
    publisher: string;
    imageUrl: string;
  };
}

/**
 * Success response for POST /api/search/episodes (v2).
 * Corresponds to EpisodeSearchResponse in podcast-spec.
 *
 * searchRequestId: UUID generated by the backend per search request.
 * The frontend must pass it back in subsequent click log events
 * to enable query log / click log join. Do not generate a new UUID on the frontend.
 */
export interface EpisodeSearchResponse {
  status: "ok";
  searchRequestId: string;
  data: {
    page: number;
    size: number;
    total: number;
    items: EpisodeDto[];
  };
}

/**
 * Partial success response for POST /api/search/episodes (v2).
 * Returned when the embedding service is unavailable and the backend falls back to BM25.
 * Results are still returned; display the warning as a non-blocking info banner.
 */
export interface EpisodeSearchPartialResponse {
  status: "partial_success";
  searchRequestId: string;
  warning: string;
  data: {
    page: number;
    size: number;
    total: number;
    items: EpisodeDto[];
  };
}

export type EpisodeSearchResult = EpisodeSearchResponse | EpisodeSearchPartialResponse;

// Re-export LangFilter here for convenience when constructing search requests
export type { LangFilter };
